apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  labels:
    app: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - image: blackrock30/revenue-prediction:1.2
          name: mlops
          ports:
            - containerPort: 5000
              name: mlops
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mlops
  labels:
    app: mlops
spec:
  type: LoadBalancer
  selector:
    app: mlops
  ports:
    - port: 5000
      targetPort: 5000
